# Generated by Django 5.2 on 2026-07-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('content', models.TextField(default='this product is very useful for you')),
                ('image_1', models.ImageField(default='product1.jpg', upload_to='products')),
                ('image_2', models.ImageField(blank=True, default='product2.jpg', upload_to='products')),
                ('image_3', models.ImageField(blank=True, default='product3.jpg', upload_to='products')),
                ('image_4', models.ImageField(blank=True, default='product4.jpg', upload_to='products')),
                ('client', models.CharField(max_length=120)),
                ('product_url', models.CharField(max_length=120)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('category', models.ManyToManyField(to='product.category')),
            ],
        ),
    ]
