# Generated by Django 5.2 on 2026-08-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='content',
            new_name='content1',
        ),
        migrations.AddField(
            model_name='services',
            name='content2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='services',
            name='content3',
            field=models.TextField(default=''),
        ),
    ]
