# Generated by Django 5.2 on 2026-07-09 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='statue',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='statue',
            new_name='status',
        ),
    ]
