# Generated by Django 5.2 on 2026-08-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_statue_attribute_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='status',
        ),
        migrations.AddField(
            model_name='features',
            name='iamge',
            field=models.ImageField(default='feature.svg', upload_to='features'),
        ),
    ]
