# Generated by Django 5.2 on 2026-08-11 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_attribute_status_features_iamge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='features',
            old_name='iamge',
            new_name='image',
        ),
    ]
