# Generated by Django 5.2 on 2026-07-08 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='B_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='employee.jpg', upload_to='employess')),
                ('content', models.TextField(default='has good talent and knowledge')),
                ('twitter', models.CharField(blank=True, max_length=120)),
                ('instagram', models.CharField(blank=True, max_length=120)),
                ('facebook', models.CharField(blank=True, max_length=120)),
                ('linkedin', models.CharField(blank=True, max_length=120)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(to='blogs.skills')),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_1', models.ImageField(default='blog.jpg', upload_to='blogs')),
                ('description_1', models.TextField(default='In these days all people need to know')),
                ('title_2', models.CharField(blank=True, default='important', max_length=120)),
                ('description_2', models.TextField(blank=True, default='this is really important')),
                ('title_3', models.CharField(blank=True, default='focus', max_length=120)),
                ('description_3', models.TextField(blank=True, default='')),
                ('quoets', models.TextField(blank=True)),
                ('status', models.BooleanField(default=False)),
                ('image_2', models.ImageField(default='blog2.jp', upload_to='blog')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('b_category', models.ManyToManyField(to='blogs.b_category')),
                ('bloger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.employees')),
                ('tags', models.ManyToManyField(to='blogs.tags')),
            ],
        ),
    ]
