# Generated by Django 5.2 on 2026-07-09 05:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='schedule',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
