# Generated by Django 5.2 on 2026-08-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogs_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='image',
            field=models.ImageField(default='employee.jpg', upload_to='employees'),
        ),
    ]
