# Generated by Django 5.2 on 2026-08-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_employees_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='b_category',
            field=models.ManyToManyField(related_name='posts', to='blogs.b_category'),
        ),
    ]
