# Generated by Django 5.2 on 2026-08-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blogs_b_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='b_category',
            field=models.ManyToManyField(related_name='blogs', to='blogs.b_category'),
        ),
    ]
